// <auto-generated />
using System;
using FootballSchool.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FootballSchool.Migrations
{
    [DbContext(typeof(FootballSchoolContext))]
    [Migration("20260304115110_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FootballSchool.Models.Attendance", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Attendance_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AttendanceId"));

                    b.Property<string>("NoteAttendance")
                        .HasColumnType("text")
                        .HasColumnName("Note_attendance");

                    b.Property<string>("StatusAttendance")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Status_attendance");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("Student_ID");

                    b.Property<int>("TrainingId")
                        .HasColumnType("int")
                        .HasColumnName("Training_ID");

                    b.HasKey("AttendanceId")
                        .HasName("PK__Attendan__57FA4934437C3D8E");

                    b.HasIndex("StudentId");

                    b.HasIndex("TrainingId");

                    b.ToTable("Attendance");
                });

            modelBuilder.Entity("FootballSchool.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Branch_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("CityBranch")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("City_branch");

                    b.Property<string>("HouseBranch")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("House_branch");

                    b.Property<string>("NameBranch")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name_branch");

                    b.Property<string>("PhoneBranch")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Phone_branch");

                    b.Property<string>("PhotoBranch")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Photo_branch");

                    b.Property<string>("StreetBranch")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Street_branch");

                    b.HasKey("BranchId")
                        .HasName("PK__Branch__12CEB04107BE5E5D");

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("FootballSchool.Models.Coach", b =>
                {
                    b.Property<int>("CoachId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Coach_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CoachId"));

                    b.Property<string>("MiddleCoach")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Middle_coach");

                    b.Property<string>("NameCoach")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name_coach");

                    b.Property<string>("QualificationCoach")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Qualification_coach");

                    b.Property<decimal?>("SalaryCoach")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Salary_coach");

                    b.Property<string>("ScheduleCoach")
                        .HasColumnType("text")
                        .HasColumnName("Schedule_coach");

                    b.Property<string>("SpecialtyCoach")
                        .IsRequired()
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Specialty_coach");

                    b.Property<string>("SurnameCoach")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Surname_coach");

                    b.HasKey("CoachId")
                        .HasName("PK__Coach__BDB636274675589F");

                    b.ToTable("Coach");
                });

            modelBuilder.Entity("FootballSchool.Models.Facility", b =>
                {
                    b.Property<int>("FacilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Facility_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FacilityId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int")
                        .HasColumnName("Branch_ID");

                    b.Property<int>("CapacityFacility")
                        .HasColumnType("int")
                        .HasColumnName("Capacity_facility");

                    b.Property<decimal?>("CostFacility")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Cost_facility");

                    b.Property<string>("NameFacility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name_facility");

                    b.Property<string>("NumberFacility")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Number_facility");

                    b.Property<string>("StatusFacility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Status_facility");

                    b.Property<string>("TypeFacility")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Type_facility");

                    b.HasKey("FacilityId")
                        .HasName("PK__Facility__CEAA23C5BD2B8BF4");

                    b.HasIndex("BranchId");

                    b.ToTable("Facility");
                });

            modelBuilder.Entity("FootballSchool.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Payment_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("AmountPayment")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Amount_payment");

                    b.Property<DateOnly>("DatePayment")
                        .HasColumnType("date")
                        .HasColumnName("Date_payment");

                    b.Property<string>("MethodPayment")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Method_payment");

                    b.Property<string>("StatusPayment")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Status_payment");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("int")
                        .HasColumnName("Subscription_ID");

                    b.HasKey("PaymentId")
                        .HasName("PK__Payment__DA6C7FE17E85319F");

                    b.HasIndex("SubscriptionId");

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("FootballSchool.Models.Progress", b =>
                {
                    b.Property<int>("ProgressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Progress_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProgressId"));

                    b.Property<string>("CommentProgress")
                        .HasColumnType("text")
                        .HasColumnName("Comment_progress");

                    b.Property<DateOnly>("DateProgress")
                        .HasColumnType("date")
                        .HasColumnName("Date_progress");

                    b.Property<string>("PhysicalProgress")
                        .HasColumnType("text")
                        .HasColumnName("Physical_progress");

                    b.Property<string>("PlanProgress")
                        .HasColumnType("text")
                        .HasColumnName("Plan_progress");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("Student_ID");

                    b.Property<string>("TestsProgress")
                        .HasColumnType("text")
                        .HasColumnName("Tests_progress");

                    b.HasKey("ProgressId")
                        .HasName("PK__Progress__D558799A376577B4");

                    b.HasIndex("StudentId");

                    b.ToTable("Progress");
                });

            modelBuilder.Entity("FootballSchool.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Student_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<string>("ApartmentStudent")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Apartment_student");

                    b.Property<DateOnly>("BirthStudent")
                        .HasColumnType("date")
                        .HasColumnName("Birth_student");

                    b.Property<string>("CityStudent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("City_student");

                    b.Property<string>("EmailStudent")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Email_student");

                    b.Property<string>("GenderStudent")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Gender_student");

                    b.Property<string>("HouseStudent")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("House_student");

                    b.Property<string>("LevelStudent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Level_student");

                    b.Property<string>("MedicalStudent")
                        .HasColumnType("text")
                        .HasColumnName("Medical_student");

                    b.Property<string>("MiddleParent")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Middle_parent");

                    b.Property<string>("MiddleStudent")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Middle_student");

                    b.Property<string>("NameParent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name_parent");

                    b.Property<string>("NameStudent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Name_student");

                    b.Property<string>("ParentNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Parent_number");

                    b.Property<string>("PhoneStudent")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("Phone_student");

                    b.Property<string>("PhotoStudent")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Photo_student");

                    b.Property<string>("StreetStudent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Street_student");

                    b.Property<string>("SurnameParent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Surname_parent");

                    b.Property<string>("SurnameStudent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Surname_student");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("Team_ID");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    b.HasKey("StudentId")
                        .HasName("PK__Student__A2F4E9AC4021C8FB");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Student");
                });

            modelBuilder.Entity("FootballSchool.Models.Subscription", b =>
                {
                    b.Property<int>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Subscription_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SubscriptionId"));

                    b.Property<decimal?>("CostSubscription")
                        .HasColumnType("decimal(10, 2)")
                        .HasColumnName("Cost_subscription");

                    b.Property<int?>("DaysSubscription")
                        .HasColumnType("int")
                        .HasColumnName("Days_subscription");

                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("Student_ID");

                    b.Property<string>("TermsSubscription")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("Terms_subscription");

                    b.Property<string>("TypeSubscription")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Type_subscription");

                    b.HasKey("SubscriptionId")
                        .HasName("PK__Subscrip__518059B16793CE27");

                    b.HasIndex("StudentId");

                    b.ToTable("Subscription");
                });

            modelBuilder.Entity("FootballSchool.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Team_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TeamId"));

                    b.Property<string>("CategoryTeam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Category_team");

                    b.Property<string>("StatusTeam")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("Status_team");

                    b.HasKey("TeamId")
                        .HasName("PK__Team__02215C0AA6728748");

                    b.ToTable("Team");
                });

            modelBuilder.Entity("FootballSchool.Models.Training", b =>
                {
                    b.Property<int>("TrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Training_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TrainingId"));

                    b.Property<int>("CoachId")
                        .HasColumnType("int")
                        .HasColumnName("Coach_ID");

                    b.Property<DateOnly>("DateTraining")
                        .HasColumnType("date")
                        .HasColumnName("Date_training");

                    b.Property<int>("FacilityId")
                        .HasColumnType("int")
                        .HasColumnName("Facility_ID");

                    b.Property<string>("PlanTraining")
                        .HasColumnType("text")
                        .HasColumnName("Plan_training");

                    b.Property<int>("TeamId")
                        .HasColumnType("int")
                        .HasColumnName("Team_ID");

                    b.Property<TimeOnly>("TimeTraining")
                        .HasColumnType("time")
                        .HasColumnName("Time_training");

                    b.HasKey("TrainingId")
                        .HasName("PK__Training__EF9C38168C9E7A2D");

                    b.HasIndex("CoachId");

                    b.HasIndex("FacilityId");

                    b.HasIndex("TeamId");

                    b.ToTable("Training");
                });

            modelBuilder.Entity("FootballSchool.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("User_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Parent");

                    b.HasKey("UserId")
                        .HasName("PK_User");

                    b.ToTable("User");
                });

            modelBuilder.Entity("FootballSchool.Models.Attendance", b =>
                {
                    b.HasOne("FootballSchool.Models.Student", "Student")
                        .WithMany("Attendances")
                        .HasForeignKey("StudentId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Student");

                    b.HasOne("FootballSchool.Models.Training", "Training")
                        .WithMany("Attendances")
                        .HasForeignKey("TrainingId")
                        .IsRequired()
                        .HasConstraintName("FK_Attendance_Training");

                    b.Navigation("Student");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("FootballSchool.Models.Facility", b =>
                {
                    b.HasOne("FootballSchool.Models.Branch", "Branch")
                        .WithMany("Facilities")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Facility_Branch");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("FootballSchool.Models.Payment", b =>
                {
                    b.HasOne("FootballSchool.Models.Subscription", "Subscription")
                        .WithMany("Payments")
                        .HasForeignKey("SubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Payment_Subscription");

                    b.Navigation("Subscription");
                });

            modelBuilder.Entity("FootballSchool.Models.Progress", b =>
                {
                    b.HasOne("FootballSchool.Models.Student", "Student")
                        .WithMany("Progresses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Progress_Student");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FootballSchool.Models.Student", b =>
                {
                    b.HasOne("FootballSchool.Models.Team", "Team")
                        .WithMany("Students")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("FK_Student_Team");

                    b.HasOne("FootballSchool.Models.User", "User")
                        .WithMany("Students")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK_Student_User");

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FootballSchool.Models.Subscription", b =>
                {
                    b.HasOne("FootballSchool.Models.Student", "Student")
                        .WithMany("Subscriptions")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Subscription_Student");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("FootballSchool.Models.Training", b =>
                {
                    b.HasOne("FootballSchool.Models.Coach", "Coach")
                        .WithMany("Training")
                        .HasForeignKey("CoachId")
                        .IsRequired()
                        .HasConstraintName("FK_Training_Coach");

                    b.HasOne("FootballSchool.Models.Facility", "Facility")
                        .WithMany("Training")
                        .HasForeignKey("FacilityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Training_Facility");

                    b.HasOne("FootballSchool.Models.Team", "Team")
                        .WithMany("Training")
                        .HasForeignKey("TeamId")
                        .IsRequired()
                        .HasConstraintName("FK_Training_Team");

                    b.Navigation("Coach");

                    b.Navigation("Facility");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("FootballSchool.Models.Branch", b =>
                {
                    b.Navigation("Facilities");
                });

            modelBuilder.Entity("FootballSchool.Models.Coach", b =>
                {
                    b.Navigation("Training");
                });

            modelBuilder.Entity("FootballSchool.Models.Facility", b =>
                {
                    b.Navigation("Training");
                });

            modelBuilder.Entity("FootballSchool.Models.Student", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Progresses");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("FootballSchool.Models.Subscription", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("FootballSchool.Models.Team", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Training");
                });

            modelBuilder.Entity("FootballSchool.Models.Training", b =>
                {
                    b.Navigation("Attendances");
                });

            modelBuilder.Entity("FootballSchool.Models.User", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
